### ISSUE TITLE
sep with python 3.3.5 (anaconda for Mac OS X)

### ISSUE THREAD

**Issue by stefanocovino** [kbarbary/sep#23]
Dear friends,

I have problems with sep trying to derive aperture photometry.

For any FITS image I could try, it happens that I always get this error message in a command like this:

f,ef,fl = sep.sum_circle(data,290.0,491.1,6b,kgann=(10,15),gain=1)

where of course data is the image, and the other parameters are the position of the object I want to measure.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sep.pyx", line 771, in sep.sum_circle (sep.c:7444)
  File "sep.pyx", line 262, in sep._parse_arrays (sep.c:3235)
  File "sep.pyx", line 180, in sep._get_sep_dtype (sep.c:2518)
ValueError: Input array with dtype '>f4' has non-native byte order. Only native byte order arrays are supported. Arrays can be converted to native byte order in-place with 'a = a.byteswap(True).newbyteorder()'

If I then follow the suggestion, I no more get error but the results are quite unreliable. 

datasw = data.byteswap(True).newbyteorder()

f,ef,fl = sep.sum_circle(datesw,290.0,491.1,6,bkgann=(10,15),gain=1.)
f,ef,fl
(array(1937628.483360562), array(1992936.1595717354), array(0, dtype=int16))

Am I doing anything wrong?

Thanks,
  Stefano

**Comment by kbarbary** [comment]
It's not obvious what the problem is here, but problems often arise from byteswapping in place (e.g., if you have any other references to `data`, they will be turned into nonsense arrays). Try doing
```
datasw = data.byteswap(False).newbyteorder()
```

Perhaps the suggestion in the ValueError should say this by default.

**Comment by stefanocovino** [comment]
> It's not obvious what the problem is here, but problems often arise from byteswapping in place (e.g., if you have any other references to data, they will be turned into nonsense arrays). Try doing
> 
> datasw = data.byteswap(False).newbyteorder()
> Perhaps the suggestion in the ValueError should say this by default.
> 
> 
Hi,

apparently the result is the same. As a matter of fact, the total flux is fine, the error however is really wrong. 

	Stefano

**Comment by kbarbary** [comment]
There is a bug in the error calculation: [this line](https://github.com/kbarbary/sep/blob/14edd19341f7a95bddde5c5c6e591d3a77f7419e/sep.pyx#L863) is missing a sqrt. Thanks for discovering this!

Will fix. In the meantime, I think taking the sqrt of the returned error should give the true error.

**Comment by stefanocovino** [comment]
Glad to help!

One last question, if I can bore you again.
It seems weird (to me) that I have to convert data read with standard tools (e.g. astropy.io.fits) for working with sep. Is there a specific reason for that?

Thanks,
   Stefano 

Mobilis in Mobile

**Comment by kbarbary** [comment]
There's a reason, but it's not a great one, and I am thinking about changing it. Here is the story:

FITS files are stored in big-endian byte order. All modern CPUs are little-endian byte order, so at *some point* you have to byteswap the data. Some FITS readers (cfitsio, the fitsio python module) do the byteswap when reading the data from disk to memory, so you get numpy arrays in native (little-endian) byte order.  On the other hand, astropy.io.fits does not byteswap for you, and you get numpy arrays in non-native byte order. However, most of the time you never notice this because when you do any numpy operations on such arrays, numpy uses an intermediate buffer to byteswap the array behind the scenes and returns the result as a native byte order array.

Within SEP, we're not using numpy operations, we're just getting a pointer to the data in the array and passing it to C code, so we can't take advantage of the fancy buffering byteswapping numpy does. We could write our own buffer code, but that would be work. A simpler option would be to check if the array is non-native byte order, and if so, make a byteswapped copy of the entire array. Easier to code, but higher memory use. In addition, this would have to be done repeatedly in multiple SEP functions: `Background`, `extract`, `sum_circle`, etc. Each would make a copy of the entire data array.

I wanted SEP to be extremely high-performance like SExtractor itself, including minimal memory usage. Repeatedly making a copy of the entire data array without the user knowing seemed like a bad idea - it seemed better to explicitly tell the user to do the byteswap operation themselves so they could just do it once.

The ideal solution in my mind would be for astropy.io.fits to return native byte order arrays. I doubt that change will happen though, so maybe SEP should allow non-native byte order arrays somehow.

**Comment by stefanocovino** [comment]
I indeed see the point.

Thanks a lot,
   Stefano

Mobilis in Mobile

**Comment by kbarbary** [comment]
Fixed and bugfix release v0.4.1 out.
