### ISSUE TITLE
Test failure on mac

### ISSUE THREAD

**Issue by mwcraig** [kbarbary/sep#30]
One of tests in `test_vs_sextractor`. With numpy 1.10 on python 3.5 I get this failure:

```python
>       assert_allclose(2.5*kr, refobjs['kron_radius'], rtol=0.01)
E       AssertionError:
E       Not equal to tolerance rtol=0.01, atol=0
E
E       (mismatch 2.941176470588232%)
E        x: array([  6.254031,   3.129915,   4.584253,   6.265339,   2.949411,
E                1.228353,   5.628618,   6.199599,   5.66083 ,   1.75581 ,
E                2.42756 ,   2.707788,   4.881667,   6.570307,   5.500608,...
E        y: array([  6.25,   3.13,   4.58,   6.27,   2.95,   1.23,   5.63,   6.39,
E                5.66,   1.76,   2.43,   2.71,   4.88,   6.57,   5.5 ,   3.87,
E                3.28,   5.77,   4.16,  11.79,   9.37,   2.91,   5.22,   5.36,...
```

**Comment by kbarbary** [comment]
I admit to setting `rtol` for these tests based on how close I got the results locally. :)

The one entry in the quoted printout that is discrepant (6.39 vs 6.1995...) happens to have a flag=2 in sextractor (based on `data/image.cat`), which means that it was deblended from another object. deblending uses a random number generator, so its likely that this object had different member pixels in the sextractor reference run versus the sep results, simply due to random values.

The different results on linux vs osx might be due to getting a different set of random values from the c library after calling `seed(0)`.

**Comment by kbarbary** [comment]
This seems to indeed have been due to deblending. Fixed by turning off deblending in the test (see #32, specifically b58a565).
