### ISSUE TITLE
PSF photometry in SEP

### ISSUE THREAD

**Issue by MickaelRigault** [kbarbary/sep#36]
Dear users,

I know SEP is suppose to be some kind of python-clone of Sextractor, and I am now using it a lot. However, I think it would be more than great to go a bit further, and SEP would strongly gain by have PSF photometry encoded.

Would that be possible ?

**Comment by kbarbary** [comment]
Hi Mickael, it's something I've thought about and even started working on at one point. However, I abandoned it as something that would be better done in a separate package.

The thing is, there are two steps to "doing" PSF photometry (in optical/NIR wide field images): (1) modeling the PSF based on "known" or suspected point sources, possibly as a function of image position or other parameters such as brightness and (2) fitting the position and amplitude of that model to individual point sources. Step 2 is the "simpler" part I thought about including in SEP, but it turns out that the implementation is tightly coupled to the model used for step 1. For step 1, there are many different ways to model the PSF and to sample that model onto a pixel grid, none of which are "absolutely" correct. Because of the tight coupling, it makes sense to implement both step 1 and step 2 in the same package (one which defines one or more types of PSF model parameterizations). Because that is pretty significant functionality and because it would have no interdependence on anything in SEP, it should be a separate package.

I would love to see a package called something like `psfmodels` that implements several different ways of modeling the PSF. A starting point could be the model(s) used in PSFEx. Those models are described in detail in the PSFEx manual, so they could even be implemented without reading any of the PSFEx code (and hence the package could have a more liberal license than the (L)GPL).

Unfortunately I don't personally have an immediate need for PSF photometry, so I can't really work on this sort of project at the moment.
